name: Package Application with PyInstaller

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2

      - name: Set up Python
        uses: actions/setup-python@v6.2.0
        with:
          python-version: '3.13'

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install dependencies
        run: uv sync --locked

      - name: Run tests
        run: uv run python -m pytest

      - name: Package Application with PyInstaller
        run: uv run pyinstaller MAMEStates.spec

      - name: Archive Bundle (Windows)
        shell: pwsh
        run: |
          Compress-Archive -Path dist/MAMEStates -DestinationPath "MAMEStates-${{ github.ref_name }}-windows.zip"

      - name: GH Release
        uses: softprops/action-gh-release@v2.5.0
        with:
          files: "MAMEStates-${{ github.ref_name }}-windows.zip"