name: Package Application with PyInstaller
on:
  push:
    tags:
      - "v*.*.*"
  
jobs:
  build:
    runs-on: windows-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v6.0.2

      - name: Set up Python
        uses: actions/setup-python@v6.2.0
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: >
          python -m pip install --upgrade pip

          pip install -r requirements.txt  

      - name: Package Application with PyInstaller
        run: |
          pyinstaller gui.spec
      - name: GH Release
        uses: softprops/action-gh-release@v2.5.0
        with:
          tag_name: 'v1.0.0-alpha'
          files: dist/gui

            

      # - name: Upload artifact
      #   uses: actions/upload-artifact@v7.0.0
      #   with:
      #     name: MAMEStates
      #     path:
      
